### ISSUE TITLE
Update ruby version to latest (2.7.x)

### ISSUE THREAD

**Issue by anelson425** [cerner/cerner.github.io#108]
Ruby 2.2.3 is out of date and we should update to a newer version to build off of

**Comment by cchesser** [comment]
The version of Ruby is quite stale with this project, as well as, the gems supporting the project. I'm planning to update these to get them more current, as I'm noticing some issues with referencing some of these older dependencies (specifically yajl-ruby @ 1.1.0).

**Comment by cchesser** [comment]
Closing this out in favor of our work on #136 (which will transition to Hugo and no longer use Ruby).
