### ISSUE TITLE
Major Uplift Discussion

### ISSUE THREAD

**Issue by alex-bezek** [cerner/cerner.github.io#134]
As this [comment](https://github.com/cerner/cerner.github.io/issues/108#issuecomment-614669460) notes, quite a few dependencies in this repo are pretty out of date.

Some of the major dependencies are
* Ruby
  * Current: [2.2.3](https://github.com/cerner/cerner.github.io/blob/16bcfff2b09279623cdd795c443d151ed6246b78/.ruby-version#L1)
  * Latest: [2.7.1](https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-7-1-released/)
* Jekyll
  * Current: [0.12.1](https://github.com/cerner/cerner.github.io/blob/16bcfff2b09279623cdd795c443d151ed6246b78/Gemfile.lock#L19)
  * Latest: [4.0.0](https://rubygems.org/gems/jekyll/versions/4.0.0)
* Bootstrap
  * Current: [v2.2.2](https://github.com/cerner/cerner.github.io/blob/16bcfff2b09279623cdd795c443d151ed6246b78/sass/bootstrap/bootstrap.scss#L2)
  * Latest: [4.4.0](https://getbootstrap.com/docs/4.4/getting-started/introduction/)

Other gems

```
bundle outdated --only-explicit --filter-major
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...

Outdated gems included in the bundle:
  * compass (newest 1.0.3, installed 0.12.2, requested ~> 0.12.2) in groups "development"
  * haml (newest 5.1.2, installed 3.1.8, requested ~> 3.1.7) in groups "development"
  * jekyll (newest 4.0.0, installed 0.12.1, requested ~> 0.12) in groups "development"
  * json (newest 2.3.0, installed 1.8.6, requested ~> 1.8) in groups "development"
  * liquid (newest 4.0.3, installed 2.3.0, requested ~> 2.3.0) in groups "development"
  * pygments.rb (newest 1.2.1, installed 0.3.7, requested ~> 0.3.4) in groups "development"
  * rake (newest 13.0.1, installed 0.9.6, requested ~> 0.9) in groups "development"
  * sinatra (newest 2.0.8.1, installed 1.4.8, requested ~> 1.4.2) in groups "default"
  * stringex (newest 2.8.5, installed 1.4.0, requested ~> 1.4.0) in groups "development"
  ```

  We were discussing amongst a few of us and were wondering if it is worth the effort to update these dependencies, or if it's time to consider moving to something newer. The idea of moving to hugo has been thrown around a bit if we just want to get onto something newer and easier to install/run. We've also talked a bit about moving to something that would allow for blog posts to be created via a CMS (whether headless and triggering builds of a static site or a fully managed blogging platform).

  Some of these options are going to be way more work than others. It's probably important to understand what the groups goals are. For example unless we want to overhauling the look and feel, it might be good to stay on our old version of bootstrap so we don't have to open that can of worms. I think the cheapest option by far is going to be to just upgrade our dependencies, but i haven't done much investigation and maybe upgrading from jekyll 0.12 to jekyll 4 is going to be just as hard as moving to a new framework. It would probably depend on the passivity of the plugins.

**Comment by alex-bezek** [comment]
Pending more discussion on https://github.com/cerner/cerner.github.io/issues/136 as it might be the answer

**Comment by cchesser** [comment]
I'm going to close this out, as we are doing a full uplift of the site with the Hugo transition (#136). This avoids all the uplift work mentioned here.
