### ISSUE TITLE
Easier Blog Previewing while writing

### ISSUE THREAD

**Issue by alex-bezek** [cerner/cerner.github.io#135]
Currently the way someone has to go about writing a new post is to run the site locally, edit the markdown, and preview it locally. It would be ideal if we could eliminate some of these steps so its easier for people to contribute content.

Before we dive into proposals, I think it would be good to understand what problems people want to solve and what amount of change we are comfortable with. For example if just making it so you don't have to run things locally but instead can create some markdown in the Github UI in a branch and it deploys your branch so you can view it, is that good enough? Or would the feedback loop be too slow? Or is our actual goal to get away from having to use markdown as its not user friendly for people unfamiliar with it? If we are wanting to not have to write markdown are we wanting to maintain the same look and feel of the site and want to investigate a headless CMS? Or do we want to consider a full fledged service.

**Comment by alex-bezek** [comment]
We've had some discussion around this and we have been thinking that the hurdle of using markdown shouldn't be a big deal. We can easily document a quick cheat sheet like github has for common blog post markdown styles that anyone can use. This combined with an automated branch deploy system should allow most people to build out posts without having to use a local development environment. Adding images is the one thing i'll need to look into.

The previewing ideas we are also talking about maybe just forking the repo internally to allow people to play around with posts and ideas internally before officially proposing them to the blog.

**Comment by cchesser** [comment]
With our changes on the Hugo transition (#136), I think we will be able to accomplish this thanks to @mjhenkes changes for pull request deploy (#141).

We should close this out on the completion of #136.

**Comment by cchesser** [comment]
Closing this out as these changes have been merged into source for the support of Hugo: 1a72b67a1b0fd61b27e9ac4cc312a9dadbf1f7e8
