### ISSUE TITLE
Investigate and correct f-twelve links to their demo

### ISSUE THREAD

**Issue by cchesser** [cerner/cerner.github.io#157]
It appears that f-twelve from our OSS blog post has a broken link to their demo:

https://engineering.cerner.com/blog/introducing-f-twelve-an-open-source-dev-console/

It appears they may be using GH pages for publishing this, which would require repository setting changes when they moved from master -> main.

Demo index.html file is here: https://github.com/cerner/f-twelve/blob/main/demo/index.html

It is assumed this demo would not be hosted in the blog site, but since the we are using the DNS record to point to GitHub for our organizational site page, these others can be referenced (like beadledom's documentation: https://engineering.cerner.com/beadledom/4.1/docs/)

**Comment by cchesser** [comment]
@mjhenkes, with the sites moving from master -> main branch, are you aware if we verified if repos were publishing their own content on GHPages, which would have required configuration changes to make that work? In this case, we would need to update the publishing source:

https://docs.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

**Comment by mjhenkes** [comment]
For sites publishing to their gh-pages branch, no changes are needed, that was the case with terra. In the case of f-twelve, they do not have gh-pages enabled on their repo.

**Comment by mjhenkes** [comment]
I think what may have happened was that gh-pages was pointing to the master branch, when it was deleted gh-pages was disabled. I've updated the repo settings to point to the main branch and am waiting on a gh-pages deploy to verify.

**Comment by mjhenkes** [comment]
It's fixed sorta, the demo is reachable from https://engineering.cerner.com/f-twelve/demo/index.html
but not from https://engineering.cerner.com/f-twelve/demo/

gh-pages must not automatically resolve to index.html in sub folders.

**Comment by cchesser** [comment]
Interesting. I may look at this some more, before we update the link (as the links on the f-twelve project need to be updated too).

**Comment by cchesser** [comment]
Thanks @mjhenkes for looking into this!

**Comment by cchesser** [comment]
Thanks @mjhenkes, it is now working for https://engineering.cerner.com/f-twelve/demo/. When reading other StackOverflow threads on this, there was a delay from this working on pages - where they just gave some additional time, and it started working.

Closing this out as there are no changes to fix our site references and do not have to log an issue to the repo for fixing their links.
