### ISSUE TITLE
Address navigation bar design

### ISSUE THREAD

**Issue by kpshek** [cerner/cerner.github.io#30]
- Navigation bar should be increased in height to at least 70px.
- Navigation links should span bar and should be white.

**Comment by cchesser** [comment]
I'm going to close this out in favor of the site redesign we are doing on #136. 

From early feedback from others, this newer theme is desirable. We will plan to get more feedback before applying it, but it definitely makes more content visible with an emphasis on the blog post content (whereas before there was much more space consumed in the navigation).

Early example of the layout:
![Screen Shot 2020-07-14 at 11 50 41 PM](https://user-images.githubusercontent.com/2358324/87504740-e325fe00-c62c-11ea-8e3e-dfe7c898b192.png)
