### ISSUE TITLE
Fix culture page styling issues

### ISSUE THREAD

**Issue by kpshek** [cerner/cerner.github.io#35]
- Section Titles should be increased by at least one increment.
- Padding between text and section containers can be reduced by 5-10 pixels.
- “Stretch yourself as a dev” section image needs to be adjusted to fill space better (refer to mockups)

Alan and Grace at the bottom were a cool addition and provide more context/explanation to the header images. Maybe we can’t reveal them with elastic scrolling they can get their own section?

**Comment by cchesser** [comment]
Closing this out as we have changed this formatting in #136, though left much of the same content. Created a new issue to revisit content on the Culture page, as when we shared this with others, there were thoughts on a content refresh. #142 

## Before
![Screen Shot 2020-07-14 at 11 57 11 PM](https://user-images.githubusercontent.com/2358324/87505297-23d24700-c62e-11ea-9ac8-20675bdec7c7.png)

## After

![Screen Shot 2020-07-14 at 11 56 35 PM](https://user-images.githubusercontent.com/2358324/87505290-203ec000-c62e-11ea-8388-529057b22cab.png)
