### ISSUE TITLE
Correct grouping of header and icon on culture page on small screens

### ISSUE THREAD

**Issue by jfewins** [cerner/cerner.github.io#37]
The header, image, and paragraph alignment of the culture page on the desktop view doesn't transform properly when the view is adjusted to small screens.  The header, image, and paragraph should remain grouped together.

Desktop:
![culture-desktop](https://cloud.githubusercontent.com/assets/1354945/13437840/e966d044-dfab-11e5-80de-9e196892f3a7.png)

Mobile:
![culture-mobile](https://cloud.githubusercontent.com/assets/1354945/13437847/eebbb8f2-dfab-11e5-9d5d-b5267f1b34f6.png)

**Comment by nithinchandrasr** [comment]
Grouping heading,image and description in one span4 div will help to keep them grouped.Hope this works.Reference: http://getbootstrap.com/2.3.2/examples/hero.html  -  3 column structure in bootstrap 2.x template. 

`<div class="row-fluid">
  <div class="span4"><h2>heading1</h2> <img src="" alt="image1"><p>description</p> </div>
  <div class="span4"><h2>heading2</h2> <img src="" alt="image2"><p>description</p> </div>
<div class="span4"><h2>heading3</h2> <img src="" alt="image3"><p>description</p> </div>
</div>`

**Comment by Nino55N** [comment]
I think this issue was fixed with: https://github.com/cerner/cerner.github.io/pull/56

**Comment by anelson425** [comment]
It was, thanks for helping out @Nino55N
