### ISSUE TITLE
Cerner Speaker Tab

### ISSUE THREAD

**Issue by heatherBoveri** [cerner/cerner.github.io#54]
Support new Cerner Speaker tab to show embedded youtube

**Comment by LindsayUllyot** [comment]
@hCarmitchel I wanted to follow up on this. Is there anything you need from us on this to move forward? Please let me know.

**Comment by cchesser** [comment]
I'm going to go ahead and close this out, as we are uplifting this to reference the CernerEng YouTube channel + Tech Talk playlist in the site uplift on #136.

We can create a new issue in the future if there are other refinements for how we are embedding YouTube content from our CernerEng channel.
