### ISSUE TITLE
Open Source Icon

### ISSUE THREAD

**Issue by LindsayUllyot** [cerner/cerner.github.io#61]
Can we add the Beadledom icon and description to the open source page, @kallie-riff @hCarmitchel?

**Icon**: http://ip-visprod/adobe/SolutionBranding/OpenSourceProjectGraphics/Beadledom/
 
**Description**: 
Beadledom is a bundle of common components required for building JAX-RS web services. It is the starting point for new services. The core of Beadledom provides health checks, monitoring via Stagemonitor, API docs via Swagger, JSON serialization via Jackson, and integration of these components with Guice.

**Comment by Kallie-Riff** [comment]
Working on this!

**Comment by Kallie-Riff** [comment]
![image](https://cloud.githubusercontent.com/assets/7071773/24675926/99fe511e-1946-11e7-93c4-b223063af03c.png)

This is what the page will look like with odd number of icons. I can leave the open space in any location but thought this looked most balanced. Thoughts?

**Comment by LindsayUllyot** [comment]
@Kallie-Riff Looks good! We've got another icon coming very soon so it will end up making the page symmetrical once we add it. Thanks!

**Comment by LindsayUllyot** [comment]
@Kallie-Riff Here's the Terra description: Terra offers a set of configurable React components designed to help build scalable and modular application UIs. The library easily integrates with webpack-based workflows and was created to solve real-world issues in projects we work on day to day.

@Kallie-Riff - Do you have a timeframe in which we could get the new icons published? Thanks for the help!

**Comment by Kallie-Riff** [comment]
@LindsayUllyot Pull request is out now! That was the last bit of information I was needing. Sorry this took a couple days. I got a new device and had to do environment setup again.

Let me know when we can fill that space in the middle! Thanks!

**Comment by anelson425** [comment]
This has been merged as part of https://github.com/cerner/cerner.github.io/pull/73
