### ISSUE TITLE
New Open Source Icon: jwala

### ISSUE THREAD

**Issue by LvBromberg** [cerner/cerner.github.io#79]
Name: jwala

Image location: [https://wiki.ucern.com/pages/viewpage.action?spaceKey=UserExperience&title=Open+Source+Project+Graphics]

Description: Jwala is a web application that provides management for a group of Tomcat servers. Jwala is capable of creating and persisting definitions of Group instances, and exposes a RESTful interface to do so. The definition of a Group includes Web Apps, JVMs, Web Servers, and Resources.

@kallie-Riff and @hCarmitchel can you please help add this icon and description to the EH blog?

**Comment by cchesser** [comment]
This was resolved with #80. Site has been deployed, and changes can now be viewed on http://engineering.cerner.com/open_source/.
