### ISSUE TITLE
New Open Source Icon: Bunsen

### ISSUE THREAD

**Issue by LvBromberg** [cerner/cerner.github.io#94]
Name: Bunsen

Image: 
![bunsen](https://user-images.githubusercontent.com/3718231/37476088-46c574f8-2842-11e8-9e69-d23bf8c86135.png)

Description: Bunsen integrates Apache Spark and FHIR, combining Spark's scalable processing advantages with FHIR's well-defined and curated data. This enables a number of deep analytic and machine learning workloads that can be ported across systems.

@Kallie-Riff said she may be able to help with adding this, please let us know if not and we can get another person to assist. Possibly @anelson425 can?

Thanks in advance!

**Comment by anelson425** [comment]
I can try to do this soon but if @Kallie-Riff can get to it first, I might just default to her.

**Comment by Kallie-Riff** [comment]
Hello @LvBromberg & @anelson425 ! I'm working on getting setup again as I had scrapped my local copy of the blog. Had some expected issues.  RedCloth gem dislikes my virtual machine for some reason. I had this same issue before. Hopefully I can get it worked out soon!

**Comment by Kallie-Riff** [comment]
@LvBromberg @anelson425 I'm still working on setup, unfortunately. 
I didn't have any issues with RedCloth this time. It's a completely different set of problems I'm having with my VM linux version, rvm, and ruby. I would still like to take this issue though! Just wanted to let you know I'm still on it. If you need this done sooner and need to get someone else on it asap - I totally understand.

**Comment by LvBromberg** [comment]
@Kallie-Riff any update on this? If you are still having issues, I can see if @anelson425 can try to get this done. I appreciate your willingness to try but I don't want you to have to jump through more hoops for it!

**Comment by Kallie-Riff** [comment]
Sorry @LvBromberg! 
Thanks @anelson425 for putting this up! Are you doing this work on a windows machine? If you are what's your secret to setup?

**Comment by anelson425** [comment]
> Sorry @LvBromberg!
Thanks @anelson425 for putting this up! Are you doing this work on a windows machine? If you are what's your secret to setup?

My secret is using a Mac for sure. But if you are using Windows, have you tried the windows subsystem for linux?
